version: '3'
services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: posture-correction-backend-api
    ports:
      - "3100:3000"
    volumes:
      - ./api:/app
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - posture-correction-backend
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
            - count: 1
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia

  db:
    build:
      context: db
      dockerfile: Dockerfile
    container_name: posture-correction-backend-db
    ports:
      - "3101:3306"
    volumes:
      - ./db/data:/var/lib/mysql
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysql", "-u${MARIADB_USER}", "-p${MARIADB_PASSWORD}", "-e", "show databases;", "posture_correction_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - posture-correction-backend

networks:
  posture-correction-backend:
    driver: bridge
