name: Generate and Push OpenAPI Schema on Develop Branch

on:
  pull_request:
    branches:
      - develop
    types:
      - closed
  push:
    branches:
      - develop

jobs:
  generate-and-push:
    runs-on: ubuntu-latest

    steps:
      # コードのチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # Python環境のセットアップ
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 必要な依存関係のインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api/dev.requirements.txt

      # OpenAPIスキーマをエクスポート
      - name: Export OpenAPI Schema
        working-directory: api
        env:
          MOCK_SECRET_EKY: true
        run: |
          python script.py openapi

      # Dockerのセットアップ
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Docker Hubにログイン
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Dockerイメージをビルドしてプッシュ
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./api
          file: ./api/schema.Dockerfile
          tags: |
            kntwt/posture-correction-schema:dev
            kntwt/posture-correction-schema:latest-dev
