name: Generate and Push OpenAPI Schema on Main Branch Update

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  push:
    branches:
      - main

jobs:
  generate-and-push:
    runs-on: ubuntu-latest

    steps:
      # コードのチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # Python環境のセットアップ
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 必要な依存関係のインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn

      # OpenAPIスキーマをエクスポート
      - name: Export OpenAPI Schema
        run: |
          python api/scripts/export_openapi.py

      # Dockerのセットアップ
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Docker Hubにログイン
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Dockerイメージをビルドしてプッシュ
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./api
          file: ./api/schema.Dockerfile
          tags: |
            your-docker-repo/openapi-schema:prod
            your-docker-repo/openapi-schema:latest-prod
